
### signup 
POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{
  "email": "onething10@gmail.com",
  "password": "1111",
  "name": "이원섭",
  "gender": "m",
  "profileImageURL": null
}

### login 
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
  "email": "onething10@gmail.com",
  "password": "1111"
}

### loginWithToken 
POST http://localhost:3001/api/user/login-token HTTP/1.1
content-type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDc0MzU1NTQsImV4cCI6MTY0ODY0NTE1NH0.dQq9p7b7P_Zvx6KmOnO2y_nNv7nCpIOteggDYR8hKZs; accessToken={ }


{ }