
### signup 
POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{
  "email": "onething10@gmail.com",
  "password": "1111",
  "name": "이원섭",
  "gender": "m",
  "profileImageURL": null
}

### login 
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
  "email": "onething10@gmail.com",
  "password": "1111"
}

### login-token 
POST http://localhost:3001/api/user/login-token HTTP/1.1
content-type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE0LCJlbWFpbCI6Im9uZXRoaW5nMTBAZ21haWwuY29tIiwibmFtZSI6IuydtOybkOyErSIsImlhdCI6MTY0NzY1OTQ2NiwiZXhwIjoxNjQ3NjYzMDY2fQ.JhKdFJ5KKk12weGWp8Is5gARO9SmXaCfLafnWnPNqYk; Path=/; HttpOnly,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDc2NTk0NjYsImV4cCI6MTY0ODg2OTA2Nn0.h4m5c4UCtLZV-yCUjCs5G1Hc_M5OIP4M11j14sxqNjE; Path=/; HttpOnly

{ }

### logout
POST http://localhost:3001/api/user/logout HTTP/1.1
content-type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE0LCJlbWFpbCI6Im9uZXRoaW5nMTBAZ21haWwuY29tIiwibmFtZSI6IuydtOybkOyErSIsImlhdCI6MTY0NzY1OTQ2NiwiZXhwIjoxNjQ3NjYzMDY2fQ.JhKdFJ5KKk12weGWp8Is5gARO9SmXaCfLafnWnPNqYk; Path=/; HttpOnly,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDc2NTk0NjYsImV4cCI6MTY0ODg2OTA2Nn0.h4m5c4UCtLZV-yCUjCs5G1Hc_M5OIP4M11j14sxqNjE; Path=/; HttpOnly

{ 
  "userID": 14
}